# Generated by Django 5.2.11 on 2026-04-08 21:05

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=256, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("elo_blitz", models.IntegerField(default=1200)),
                ("elo_rapid", models.IntegerField(default=1200)),
                ("elo_bullet", models.IntegerField(default=1200)),
                ("elo_classical", models.IntegerField(default=1200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="users_user_is_acti_ddda02_idx"
                    ),
                    models.Index(
                        fields=["elo_blitz"], name="users_user_elo_bli_c9c6f5_idx"
                    ),
                    models.Index(
                        fields=["elo_rapid"], name="users_user_elo_rap_30f7f1_idx"
                    ),
                    models.Index(
                        fields=["elo_bullet"], name="users_user_elo_bul_4892e1_idx"
                    ),
                    models.Index(
                        fields=["elo_classical"], name="users_user_elo_cla_885866_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("username"),
                        name="username_case_insensitive_unique",
                    )
                ],
            },
        ),
    ]
