# Generated by Django 5.2.11 on 2026-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="/avatars/b_king_avatar.png",
                max_length=255,
                null=True,
            ),
        ),
    ]
