# Generated by Django 5.2.11 on 2026-04-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_user_avatar"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_elo_cla_885866_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="elo_classical",
        ),
    ]
