upstream django_server {
    server web:8000;
}

server {
    listen 80;
    server_name welikechess-api.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name welikechess-api.duckdns.org;

    # Rutas a los certificados que acabas de generar
    ssl_certificate /etc/letsencrypt/live/welikechess-api.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/welikechess-api.duckdns.org/privkey.pem;

    location ~ ^/(admin|api/docs|api/schema) {
        allow ${ADMIN_IP};
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        deny all;

        proxy_pass http://django_server;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location / {
        proxy_pass http://django_server;
        proxy_http_version 1.1;
        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}