# Generated by Django 5.2.11 on 2026-04-08 21:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Esperando rival"),
                            ("in_progress", "En curso"),
                            ("completed", "Completada"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("bullet", "Bullet"),
                            ("blitz", "Blitz"),
                            ("rapid", "Rapid"),
                            ("classical", "Clásica"),
                        ],
                        default="blitz",
                        max_length=10,
                    ),
                ),
                ("initial_time", models.PositiveIntegerField(default=600)),
                ("increment", models.PositiveIntegerField(default=0)),
                ("ranked", models.BooleanField(default=True)),
                (
                    "current_fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=120,
                    ),
                ),
                ("pgn", models.TextField(blank=True, default="")),
                ("last_move_at", models.DateTimeField(blank=True, null=True)),
                ("white_elo_change", models.IntegerField(default=0)),
                ("black_elo_change", models.IntegerField(default=0)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("1-0", "Victoria Blancas"),
                            ("0-1", "Victoria Negras"),
                            ("1/2-1/2", "Tablas"),
                            ("*", "En curso"),
                        ],
                        default="*",
                        max_length=10,
                    ),
                ),
                (
                    "termination_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("checkmate", "Jaque Mate"),
                            ("timeout", "Tiempo agotado"),
                            ("resignation", "Abandono"),
                            ("disconnected", "Desconexión"),
                            ("draw", "Tablas"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
