# Generated by Django 5.2.11 on 2026-04-22 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="game",
            name="games_game_status_dab637_idx",
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["status", "mode", "initial_time", "increment", "created_at"],
                name="matchmaking_idx",
            ),
        ),
    ]
