# Generated by Django 5.2.11 on 2026-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_remove_game_games_game_status_dab637_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="black_time_left",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="white_time_left",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="mode",
            field=models.CharField(
                choices=[("bullet", "Bullet"), ("blitz", "Blitz"), ("rapid", "Rapid")],
                default="blitz",
                max_length=10,
            ),
        ),
    ]
