# Generated by Django 5.2.11 on 2026-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_black_disconnected_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lichess_id", models.CharField(max_length=20, unique=True)),
                ("fen", models.CharField(max_length=150)),
                ("moves", models.TextField()),
                ("rating", models.IntegerField()),
                ("themes", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["rating"], name="games_puzzl_rating_c07f90_idx"
                    )
                ],
            },
        ),
    ]
